import { MigrationInterface, QueryRunner } from 'typeorm';

export class CreateCompetenceFrameworkTable20260522000200 implements MigrationInterface {
  name = 'CreateCompetenceFrameworkTable20260522000200';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      CREATE TABLE "competence_framework" (
        "id" uuid NOT NULL DEFAULT uuid_generate_v4(),
        "layer" character varying NOT NULL,
        "hboiActivity" character varying NOT NULL,
        "level" integer NOT NULL,
        "description" text NOT NULL,
        CONSTRAINT "PK_competence_framework_id" PRIMARY KEY ("id"),
        CONSTRAINT "UQ_competence_framework_cell_level" UNIQUE ("layer", "hboiActivity", "level")
      )
    `);

    await queryRunner.query(`
      INSERT INTO "competence_framework" ("layer", "hboiActivity", "level", "description") VALUES
      ('Professional Development', 'Personal leadership', 1, 'Je bent je bewust van je eigen sterke en zwakke punten, zowel op het gebied van ICT als in je persoonlijke ontwikkeling. Je kiest acties die in lijn zijn met je kernwaarden om je persoonlijke groei te bevorderen en je leermotivatie te ontwikkelen.'),
      ('Professional Development', 'Personal leadership', 2, 'Je formuleert zelfstandig doelen en acties die leiderschap tonen in je eigen lange termijn ontwikkeling als ICT-professional. Je toont aan dat je in staat bent deze acties uit te voeren en je doelen te bereiken, en past ze indien nodig aan.'),
      ('Professional Development', 'Professional standard', 1, 'Zowel individueel als in teams pas je een relevante methodologische benadering toe die in het vakgebied wordt gebruikt om projectdoelen te formuleren, belanghebbenden te betrekken, toegepast onderzoek uit te voeren, advies te geven, beslissingen te nemen en rapporten op te stellen. Hierbij houd je rekening met de relevante ethische, interculturele en duurzame aspecten.'),
      ('Professional Development', 'Professional standard', 2, 'Je neemt verantwoordelijkheid bij het oplossen van een ICT-probleem. Je definieert en voert je onderzoek uit met behulp van relevante geselecteerde methodologieën en geeft advies aan je belanghebbenden, zelfs in complexe en onzekere contexten. Je onderbouwt en valideert toekomstgerichte keuzes met ethische, interculturele en duurzame argumenten.'),
      ('User Interaction', 'Analysis', 1, 'Voer basisanalyses uit van gebruikersinteractieprocessen, producten en informatiestromen in hun onderlinge relatie en context. Werk onder algemene richtlijnen in een gestructureerde en voorspelbare context, gericht op goed gedefinieerde problemen met bekende benaderingen en oplossingen met betrekking tot de communicatie tussen de gebruiker en het ICT-systeem.'),
      ('User Interaction', 'Analysis', 2, 'Analyses uitvoeren van gebruikersinteractieprocessen, producten en informatiestromen in hun onderlinge relatie en context in een gestructureerde maar onvoorspelbare omgeving. Gegeven problemen aanpakken met beperkte keuzes in aanpak en oplossingen, waarbij verschillende basisconcepten worden gecombineerd met enkele diepgaande concepten, en enige autonomie wordt getoond bij het oplossen van problemen die verband houden met de communicatie tussen gebruiker en ICT-systeem.'),
      ('User Interaction', 'Analysis', 3, 'Analyseer onafhankelijk gebruikersinteractieprocessen, producten en informatiestromen in hun onderlinge relatie en context in een gestructureerde maar onvoorspelbare omgeving waar problemen vaag zijn en de aanpak en oplossingsruimte open zijn. Dit vereist een combinatie van geavanceerde concepten gericht op diepere verkenning en innovatie, waardoor de communicatie tussen de gebruiker en het ICT-systeem wordt verbeterd.'),
      ('User Interaction', 'Advise', 1, 'Basisadvies geven over het organiseren van gebruikersinteractieprocessen en informatie voor nieuw ontwikkelde, aangeschafte of aangepaste ICT-systemen. Opereren volgens algemene richtlijnen in een gestructureerde, voorspelbare context, waarbij de nadruk ligt op het garanderen van effectieve communicatie tussen de gebruiker en het systeem.'),
      ('User Interaction', 'Advise', 2, 'Zelfstandig advies geven over de organisatie van gebruikersinteractieprocessen en informatie voor ICT-systemen. Werk in een gestructureerde maar onvoorspelbare context, los specifieke problemen op en geef aanbevelingen om de communicatie tussen gebruiker en systeem te verbeteren, terwijl u ervoor zorgt dat het systeem aan de behoeften van de gebruiker voldoet.'),
      ('User Interaction', 'Advise', 3, 'Autonoom uitgebreid advies geven over het optimaliseren van gebruikersinteractieprocessen en informatie voor ICT-systemen, rekening houdend met zowel de functionaliteit als de bruikbaarheid van het systeem. Opereren in een gestructureerde maar onvoorspelbare context, waarbij vage problemen worden aangepakt met innovatieve aanbevelingen om de communicatie tussen gebruiker en systeem te verbeteren.'),
      ('User Interaction', 'Design', 1, 'Ontwerp een basisinterface voor gebruikersinteractie voor een ICT-systeem of een deel daarvan, volgens vooraf bepaalde richtlijnen en vastgestelde oplossingen. Zorg ervoor dat de interface voldoet aan de essentiële gebruikersvereisten in een gestructureerde en voorspelbare context.'),
      ('User Interaction', 'Design', 2, 'Ontwerp het gebruikersinteractieaspect van een ICT-systeem, rekening houdend met zowel hardware- als softwarecomponenten. Adresseer gebruikersvereisten op basis van een vereistenanalyse, waarbij u omgaat met enige onvoorspelbaarheid in het ontwerpproces. Kies uit een beperkt aantal ontwerpbenaderingen om een ​​effectieve gebruikersinterface te creëren.'),
      ('User Interaction', 'Design', 3, 'Ontwerp een uitgebreide gebruikersinteractie-ervaring voor een gedistribueerd ICT-systeem. Ontwikkel innovatieve oplossingen op basis van een gedetailleerde analyse van de vereisten, rekening houdend met referentiearchitecturen en internationale standaarden. Hanteer onvoorspelbare contexten en vage problemen en zorg voor een naadloze en gebruiksvriendelijke interactie.'),
      ('User Interaction', 'Realisation', 1, 'Creëer en test basiscomponenten voor gebruikersinteractie van een ICT-systeem op basis van een bepaald ontwerp. Volg vastgestelde procedures om ervoor te zorgen dat de interface aan vooraf gedefinieerde vereisten voldoet. Focus op het implementeren van eenvoudige gebruikersinterface-elementen in een gestructureerde en voorspelbare context.'),
      ('User Interaction', 'Realisation', 2, 'Creëer en test gebruikersinteractie-elementen van een ICT-systeem, waarbij wordt voldaan aan specifieke ontwerpvereisten. Ga om met onvoorspelbaarheid tijdens de implementatie en selecteer geschikte methoden om effectieve communicatie tussen de gebruiker en het systeem te garanderen. Zorg ervoor dat de componenten van de gebruikersinterface aansluiten bij het algehele ontwerp en een bevredigende gebruikerservaring bieden.'),
      ('User Interaction', 'Realisation', 3, 'Creëer en test uitgebreide gebruikersinteractiecomponenten voor een ICT-systeem, op basis van gedetailleerde ontwerpspecificaties. Ontwikkel innovatieve oplossingen om de gebruikerservaring te verbeteren, waarbij u omgaat met onvoorspelbare contexten en vage vereisten. Implementeer geavanceerde gebruikersinterfacefuncties die een naadloze interactie tussen de gebruiker en het systeem garanderen.'),
      ('User Interaction', 'Manage&Control', 1, 'Beheer en bewaak de basiscomponenten van de gebruikersinteractie van een ICT-systeem. Volg de vastgestelde procedures om ervoor te zorgen dat de interface soepel werkt en voldoet aan vooraf gedefinieerde vereisten. Focus op het onderhouden van fundamentele gebruikersinterfacefunctionaliteiten in een gestructureerde en voorspelbare context.'),
      ('User Interaction', 'Manage&Control', 2, 'Beheer, monitor en optimaliseer gebruikersinteractie-elementen van een ICT-systeem, waarbij wordt ingegaan op specifieke vereisten en gebruikersfeedback. Ga om met enige onvoorspelbaarheid tijdens het proces en selecteer geschikte methoden om de prestaties van de gebruikersinterface te verbeteren en effectieve communicatie tussen de gebruiker en het systeem te garanderen.'),
      ('User Interaction', 'Manage&Control', 3, 'Houd toezicht op het beheer, de monitoring en de optimalisatie van uitgebreide gebruikersinteractiecomponenten voor een ICT-systeem. Ontwikkel en implementeer innovatieve oplossingen op basis van gedetailleerde gebruikersfeedback en prestatiegegevens. Ga om met onvoorspelbare contexten en complexe problemen en zorg ervoor dat de gebruikersinterface een naadloze en boeiende ervaring biedt.'),
      ('Software', 'Analysis', 1, 'Voer basisanalyses uit van softwareontwikkelingsprocessen, producten en informatiestromen in hun onderlinge samenhang en context. Werk onder algemene richtlijnen in een gestructureerde en voorspelbare context, met de nadruk op goed gedefinieerde problemen met bekende benaderingen en oplossingen.'),
      ('Software', 'Analysis', 2, 'Analyses uitvoeren van softwareontwikkelingsprocessen, producten en informatiestromen in hun onderlinge samenhang en context in een gestructureerde maar onvoorspelbare omgeving. Pak bepaalde problemen aan met beperkte keuzemogelijkheden in aanpak en oplossingen, combineer verschillende basisconcepten met enkele diepgaande concepten en toon enige autonomie bij het oplossen van problemen.'),
      ('Software', 'Analysis', 3, 'Analyseer zelfstandig softwareontwikkelingsprocessen, producten en informatiestromen in hun onderlinge samenhang en context in een gestructureerde maar onvoorspelbare omgeving waar problemen vaag zijn en de aanpak en oplossingsruimte open zijn. Dit vereist een combinatie van geavanceerde concepten gericht op diepere verkenning en innovatie in lokale situaties.'),
      ('Software', 'Advise', 1, 'Advies geven over het inrichten van basisprocessen en informatie voor een nieuw of aangepast softwaresysteem. Dit houdt in dat u vooraf bepaalde richtlijnen en oplossingen volgt die bekend en voorspelbaar zijn. De context is gestructureerd en de problemen zijn goed gedefinieerd, met een duidelijke aanpak om ze op te lossen.'),
      ('Software', 'Advise', 2, 'Bied advies over het organiseren van processen en informatie voor een nieuw of aangepast softwaresysteem, waarbij u kunt omgaan met enigszins onvoorspelbare veranderingen. Hoewel de context gestructureerd blijft, vereisen de gepresenteerde problemen een keuze uit een beperkt aantal benaderingen. Oplossingen moeten op maat worden gemaakt om binnen deze beperkingen te passen.'),
      ('Software', 'Advise', 3, 'Adviseren over de organisatie van processen en informatie voor een nieuw of aangepast softwaresysteem in een omgeving met onvoorspelbare contexten en vage problemen. De aanpak om deze problemen op te lossen heeft een open einde, waardoor innovatieve oplossingen op maat van de specifieke situatie mogelijk zijn.'),
      ('Software', 'Design', 1, 'Ontwerp basissoftwarecomponenten op basis van duidelijk gedefinieerde vereisten. Volg vastgestelde richtlijnen en bekende oplossingen om ervoor te zorgen dat de software na oplevering effectief kan worden geïntegreerd in de ICT-infrastructuur. De context is gestructureerd en voorspelbaar, waarbij de nadruk ligt op fundamentele softwareontwikkelingsprincipes.'),
      ('Software', 'Design', 2, 'Ontwerp software die kan worden geïntegreerd in een ICT-infrastructuur en die voldoet aan specifieke vereisten die zijn afgeleid van een grondige analyse. Ga om met enige onvoorspelbaarheid in het ontwerpproces en kies uit een beperkt aantal benaderingen om software te creëren die voldoet aan de gedefinieerde eisen en die na oplevering naadloos kan worden geïntegreerd.'),
      ('Software', 'Design', 3, 'Ontwerp integrale softwareoplossingen die passen in een bredere ICT-infrastructuur. Ontwikkel innovatieve software op basis van een gedetailleerde analyse van de vereisten, rekening houdend met verschillende interactieaspecten en zorg voor een naadloze integratie. Ga om met onvoorspelbare contexten en vage problemen en maak gebruik van geavanceerde ontwikkelingstechnieken om aanpasbare en schaalbare software te creëren.'),
      ('Software', 'Realisation', 1, 'Creëer en test basissoftwarecomponenten op basis van een bepaald ontwerp. Volg vastgestelde procedures om ervoor te zorgen dat de software na oplevering effectief kan worden geïntegreerd in de ICT-infrastructuur. Werk binnen een gestructureerde en voorspelbare context om fundamentele softwarefunctionaliteiten te ontwikkelen.'),
      ('Software', 'Realisation', 2, 'Creëer en test softwarecomponenten op basis van gedetailleerde ontwerpspecificaties, die voldoen aan specifieke vereisten. Navigeer door enige onvoorspelbaarheid tijdens het ontwikkelen en testen. Zorg ervoor dat de software soepel integreert met de bestaande ICT-infrastructuur en selecteer geschikte methoden om opkomende problemen op te lossen.'),
      ('Software', 'Realisation', 3, 'Creëer en test uitgebreide softwareoplossingen die passen in een bredere ICT-infrastructuur. Ontwikkel innovatieve software op basis van gedetailleerde ontwerpspecificaties, die rekening houdt met onvoorspelbare contexten en complexe vereisten. Implementeer geavanceerde functionaliteiten om ervoor te zorgen dat de software voldoet aan de doelstellingen van de organisatie en naadloos integreert met andere systeemcomponenten.'),
      ('Software', 'Manage&Control', 1, 'Beheer en bewaak de basisprocessen voor softwareontwikkeling en -implementatie om ervoor te zorgen dat ze aansluiten bij vooraf gedefinieerde vereisten. Volg gevestigde procedures om essentiële softwarefunctionaliteiten binnen een gestructureerde en voorspelbare context te behouden, waardoor een soepele integratie in de ICT-infrastructuur wordt gegarandeerd.'),
      ('Software', 'Manage&Control', 2, 'Beheer, monitor en optimaliseer de ontwikkeling en implementatie van softwarecomponenten. Houd rekening met specifieke vereisten en ga om met onvoorspelbaarheid tijdens het proces. Selecteer geschikte methoden om de softwareprestaties te verbeteren en een effectieve integratie met de bestaande ICT-infrastructuur te garanderen.'),
      ('Software', 'Manage&Control', 3, 'Houdt toezicht op het beheer, de monitoring en de optimalisatie van uitgebreide softwaresystemen. Ontwikkel en implementeer innovatieve oplossingen op basis van gedetailleerde prestatiegegevens en gebruikersfeedback. Ga om met onvoorspelbare contexten en complexe problemen, zorg ervoor dat de software de algemene organisatiedoelen ondersteunt en verbetert en tegelijkertijd naadloos integreert in de ICT-infrastructuur.'),
      ('Hardware Interfacing', 'Analysis', 1, 'Voer basisanalyses uit van hardware-interfaceprocessen, producten en informatiestromen in hun onderlinge relatie en context. Werk onder algemene richtlijnen in een gestructureerde en voorspelbare context, gericht op goed gedefinieerde problemen met bekende benaderingen en oplossingen, rekening houdend met de mogelijkheden en beperkingen van de beschikbare hardware.'),
      ('Hardware Interfacing', 'Analysis', 2, 'Voer analyses uit van hardware-interfaceprocessen, producten en informatiestromen in hun onderlinge relatie en context in een gestructureerde maar onvoorspelbare omgeving. Pak gegeven problemen aan met beperkte keuzemogelijkheden in aanpak en oplossingen, waarbij verschillende basisconcepten worden gecombineerd met een paar diepgaande concepten, en enige autonomie wordt getoond bij het oplossen van problemen die verband houden met hardwaremogelijkheden en -beperkingen.'),
      ('Hardware Interfacing', 'Analysis', 3, 'Analyseer onafhankelijk hardware-interfaceprocessen, producten en informatiestromen in hun onderlinge relatie en context in een gestructureerde maar onvoorspelbare omgeving waar problemen vaag zijn en de aanpak en oplossingsruimte open zijn. Dit vereist een combinatie van geavanceerde concepten gericht op diepere verkenning en innovatie, rekening houdend met de mogelijkheden en beperkingen van de beschikbare hardware.'),
      ('Hardware Interfacing', 'Advise', 1, 'Advies geven over het organiseren van processen en informatie voor een nieuw of aangepast ICT-systeem met hardware-interface. Werk binnen een gestructureerde en voorspelbare context, volgens vastgestelde richtlijnen en bekende oplossingen. Zorg ervoor dat de software voldoet aan de basishardwaremogelijkheden en -beperkingen, waarbij fundamentele concepten worden toegepast voor effectieve interactie.'),
      ('Hardware Interfacing', 'Advise', 2, 'Bied advies over het organiseren van processen en informatie voor een nieuw of aangepast ICT-systeem met hardware-interfaces, waarbij enkele onvoorspelbare veranderingen worden aangepakt. De context blijft gestructureerd, maar problemen vereisen een keuze uit een beperkt aantal benaderingen. Pas een mix van basis- en diepgaande concepten toe om de softwarefunctionaliteit af te stemmen op de hardwaremogelijkheden en -beperkingen.'),
      ('Hardware Interfacing', 'Advise', 3, 'Adviseren over het organiseren van processen en informatie voor een nieuw of aangepast ICT-systeem met hardware-interface in een context met onvoorspelbare elementen en vage problemen. Ontwikkel innovatieve oplossingen die zijn afgestemd op de specifieke hardwaremogelijkheden en -beperkingen, waarbij u verschillende geavanceerde concepten onderzoekt om de interactie tussen software en hardware te verbeteren.'),
      ('Hardware Interfacing', 'Design', 1, 'Ontwerp basissoftwarecomponenten die samenwerken met beschikbare hardware, op basis van duidelijk gedefinieerde vereisten. Volg de vastgestelde richtlijnen om ervoor te zorgen dat de software effectief rekening houdt met de mogelijkheden en beperkingen van de hardware. De context is gestructureerd en voorspelbaar, waarbij de nadruk ligt op fundamentele hardware-interfaceprincipes.'),
      ('Hardware Interfacing', 'Design', 2, 'Ontwerp software die communiceert met hardware en tegemoetkomt aan specifieke vereisten die zijn afgeleid van een grondige analyse. Ga om met enige onvoorspelbaarheid in het ontwerpproces en kies uit een beperkt aantal benaderingen om software te creëren die effectief samenwerkt met hardwaremogelijkheden en -beperkingen in contexten zoals embedded systemen of industriële automatisering.'),
      ('Hardware Interfacing', 'Design', 3, 'Ontwerp uitgebreide softwareoplossingen die communiceren met verschillende hardwarecomponenten in een breder systeem. Ontwikkel innovatieve software op basis van een gedetailleerde analyse van de vereisten, rekening houdend met de interactie tussen software en hardware in onvoorspelbare contexten. Maak gebruik van geavanceerde technieken om vage problemen aan te pakken en zorg voor een naadloze integratie en optimale prestaties van hardware-interfacesoftware.'),
      ('Hardware Interfacing', 'Realisation', 1, 'Creëer en test basiscomponenten van de ICT-infrastructuur, inclusief hardware en software, op basis van een bepaald ontwerp. Volg vastgestelde procedures om de beschikbaarheid en initiële configuratie van infrastructuurelementen te garanderen. Werk binnen een gestructureerde en voorspelbare context om organisatorische processen te ondersteunen.'),
      ('Hardware Interfacing', 'Realisation', 2, 'Creëer en test componenten van de ICT-infrastructuur, inclusief zowel hardware- als software-elementen zoals netwerkomgevingen, op basis van gedetailleerde ontwerpspecificaties. Ga in op specifieke vereisten en ga om met enige onvoorspelbaarheid tijdens de implementatie. Zorg ervoor dat de infrastructuurcomponenten beschikbaar, correct geconfigureerd en beveiligd zijn om aan de behoeften van de organisatie te voldoen.'),
      ('Hardware Interfacing', 'Realisation', 3, 'Creëer en test uitgebreide ICT-infrastructuursystemen, waarbij hardware, software en netwerkomgevingen worden geïntegreerd om organisatorische processen te ondersteunen. Ontwikkel innovatieve oplossingen op basis van gedetailleerde ontwerpspecificaties, waarbij u rekening houdt met onvoorspelbare contexten en complexe vereisten. Implementeer geavanceerde configuraties en beveiligingsmaatregelen om ervoor te zorgen dat de infrastructuur robuust is en is afgestemd op de doelstellingen van de organisatie.'),
      ('Hardware Interfacing', 'Manage&Control', 1, 'Beheer en bewaak de basisprocessen voor softwareontwikkeling en -implementatie die interageren met beschikbare hardware. Volg vastgestelde procedures om ervoor te zorgen dat de software rekening houdt met de mogelijkheden en beperkingen van de hardware. Werk binnen een gestructureerde en voorspelbare context om essentiële hardware-interfacefunctionaliteiten te behouden.'),
      ('Hardware Interfacing', 'Manage&Control', 2, 'Beheer, monitor en optimaliseer de ontwikkeling en implementatie van softwarecomponenten die communiceren met hardware. Houd rekening met specifieke vereisten en ga om met onvoorspelbaarheid tijdens het proces. Selecteer geschikte methoden om de softwareprestaties te verbeteren en zorg voor een effectieve interactie met de mogelijkheden en beperkingen van de hardware.'),
      ('Hardware Interfacing', 'Manage&Control', 3, 'Houd toezicht op het beheer, de monitoring en de optimalisatie van uitgebreide softwaresystemen die zijn ontworpen voor hardware-interfaces. Ontwikkel en implementeer innovatieve oplossingen op basis van gedetailleerde prestatiegegevens en hardwarespecificaties. Ga om met onvoorspelbare contexten en complexe problemen en zorg voor een naadloze integratie en optimale interactie tussen software en hardware in verschillende contexten, zoals embedded systemen of industriële automatisering.'),
      ('Infrastructure', 'Analysis', 1, 'Analyseer processen, producten en informatiestromen binnen ICT-systemen, met de nadruk op traditionele hardware-infrastructuur zoals netwerken. Werk onder algemene richtlijnen in een gestructureerde, voorspelbare context waarin het probleem is gedefinieerd en de aanpak en oplossing bekend zijn.'),
      ('Infrastructure', 'Analysis', 2, 'Analyseer en los problemen op die verband houden met de configuratie en het onderhoud van ICT-systemen, inclusief zowel hardware als cloudgebaseerde software-infrastructuur. Autonoom werken in een gestructureerde maar onvoorspelbare context, waar het probleem gegeven is en de keuze voor aanpak beperkt is.'),
      ('Infrastructure', 'Analysis', 3, 'Analyseer zelfstandig complexe problemen en hun onderlinge relaties binnen de ICT-infrastructuur en stel innovatieve oplossingen voor lokale situaties voor. Werken in een gestructureerde maar onvoorspelbare context met vage problemen, waarbij zowel de aanpak als de oplossingsruimte open zijn.'),
      ('Infrastructure', 'Advise', 1, 'Adviseren over de organisatie van infrastructuurprocessen en informatie voor een nieuw ontwikkeld, aangeschaft of aangepast ICT-systeem binnen een gestructureerde en voorspelbare context. Dit houdt in dat traditionele hardware- en software-infrastructuren, zoals netwerken en cloudgebaseerde omgevingen, beschikbaar zijn en op de juiste manier worden geconfigureerd. Werk volgens algemene richtlijnen waarbij veranderingen voorspelbaar zijn en het probleem en de oplossingen bekend zijn bij de klant.'),
      ('Infrastructure', 'Advise', 2, 'Adviseren over de organisatie van infrastructuurprocessen en informatie voor een nieuw ontwikkeld, aangeschaft of aangepast ICT-systeem binnen een gestructureerde maar onvoorspelbare context. Gebruik een combinatie van basis- en enkele diepgaande concepten om infrastructuurgerelateerde problemen aan te pakken en ervoor te zorgen dat hardware- en softwaresystemen, inclusief netwerken en cloudomgevingen, effectief worden beheerd. Los zelfstandig problemen op die voortvloeien uit projectactiviteiten en pas u aan aan onvoorspelbare veranderingen.'),
      ('Infrastructure', 'Advise', 3, 'Adviseren over de organisatie van infrastructuurprocessen en informatie voor een nieuw ontwikkeld, aangeschaft of aangepast ICT-systeem binnen een gestructureerde en onvoorspelbare context. Gebruik verschillende concepten om dieper in de infrastructuur te duiken en deze te innoveren, waarbij vage problemen met betrekking tot hardware- en softwaresystemen, inclusief cloudgebaseerde omgevingen, worden aangepakt met een open benadering en oplossingsruimte. Werk autonoom om interactieve problemen op te lossen, wat een positieve invloed heeft op de teamprestaties in onvoorspelbare omgevingen.'),
      ('Infrastructure', 'Design', 1, 'Ontwerp een basisonderdeel van de ICT-infrastructuur ter ondersteuning van organisatorische processen op basis van duidelijk gedefinieerde vereisten. Volg gevestigde richtlijnen en bekende oplossingen om de beschikbaarheid en configuratie van traditionele hardware- en software-infrastructuur in een gestructureerde en voorspelbare context te garanderen.'),
      ('Infrastructure', 'Design', 2, 'Ontwerp een ICT-systeem dat zowel hardware- als software-infrastructuur omvat om organisatorische processen te ondersteunen. Ga in op specifieke vereisten op basis van een grondige analyse, waarbij u omgaat met onvoorspelbaarheid. Kies uit een beperkt aantal ontwerpbenaderingen om ervoor te zorgen dat het systeem beschikbaar en correct geconfigureerd blijft.'),
      ('Infrastructure', 'Design', 3, 'Ontwerp een uitgebreid ICT-infrastructuursysteem dat traditionele hardware- en softwarecomponenten integreert om organisatorische processen te vergemakkelijken. Ontwikkel innovatieve oplossingen op basis van een gedetailleerde analyse van de vereisten, rekening houdend met de interactie tussen verschillende infrastructuurelementen. Ga om met onvoorspelbare contexten en vage problemen om een ​​robuuste en schaalbare infrastructuur te garanderen.'),
      ('Infrastructure', 'Realisation', 1, 'Creëer en test basiscomponenten van de ICT-infrastructuur, inclusief hardware en software, op basis van een bepaald ontwerp. Volg vastgestelde procedures om de beschikbaarheid en initiële configuratie van infrastructuurelementen te garanderen. Werk binnen een gestructureerde en voorspelbare context om organisatorische processen te ondersteunen.'),
      ('Infrastructure', 'Realisation', 2, 'Creëer en test componenten van de ICT-infrastructuur, inclusief zowel hardware- als software-elementen zoals netwerkomgevingen, op basis van gedetailleerde ontwerpspecificaties. Ga in op specifieke vereisten en ga om met enige onvoorspelbaarheid tijdens de implementatie. Zorg ervoor dat de infrastructuurcomponenten beschikbaar, correct geconfigureerd en beveiligd zijn om aan de behoeften van de organisatie te voldoen.'),
      ('Infrastructure', 'Realisation', 3, 'Creëer en test uitgebreide ICT-infrastructuursystemen, waarbij hardware, software en netwerkomgevingen worden geïntegreerd om organisatorische processen te ondersteunen. Ontwikkel innovatieve oplossingen op basis van gedetailleerde ontwerpspecificaties, waarbij u rekening houdt met onvoorspelbare contexten en complexe vereisten. Implementeer geavanceerde configuraties en beveiligingsmaatregelen om ervoor te zorgen dat de infrastructuur robuust is en is afgestemd op de doelstellingen van de organisatie'),
      ('Infrastructure', 'Manage&Control', 1, 'Beheer en monitor basiscomponenten van de ICT-infrastructuur, inclusief hardware en software, om de beschikbaarheid en juiste configuratie ervan te garanderen. Volg gevestigde procedures om essentiële infrastructuuractiviteiten in een gestructureerde en voorspelbare context te onderhouden.'),
      ('Infrastructure', 'Manage&Control', 2, 'Beheer, monitor en optimaliseer de ontwikkeling en inzet van ICT-infrastructuurcomponenten. Houd rekening met specifieke organisatorische vereisten en ga om met onvoorspelbaarheid tijdens het proces. Selecteer geschikte methoden om de prestaties van de infrastructuur te verbeteren en de beschikbaarheid en configuratie van zowel hardware- als software-elementen te garanderen.'),
      ('Infrastructure', 'Manage&Control', 3, 'Houdt toezicht op het beheer, de monitoring en de optimalisatie van uitgebreide ICT-infrastructuursystemen. Ontwikkel en implementeer innovatieve oplossingen op basis van gedetailleerde prestatiegegevens en organisatorische feedback. Ga om met onvoorspelbare contexten en complexe problemen en zorg ervoor dat de infrastructuur de algehele organisatieprocessen ondersteunt en verbetert.'),
      ('Organisational processes', 'Analysis', 1, 'Analyseer processen, producten en informatiestromen binnen ICT-systemen, waarbij de nadruk ligt op de functionaliteit van zowel geautomatiseerde als niet-geautomatiseerde componenten bij het bereiken van organisatiedoelstellingen. Werk onder algemene richtlijnen in een gestructureerde, voorspelbare context waarin het probleem is gedefinieerd en de aanpak en oplossing bekend zijn.'),
      ('Organisational processes', 'Analysis', 2, 'Analyseer en los problemen op die verband houden met de functionaliteit van ICT-systemen, rekening houdend met zowel geautomatiseerde als niet-geautomatiseerde componenten in de context van organisatiedoelen. Autonoom werken in een gestructureerde maar onvoorspelbare context, waar het probleem gegeven is en de keuze voor aanpak beperkt is.'),
      ('Organisational processes', 'Analysis', 3, 'Analyseer zelfstandig complexe problemen en hun onderlinge relaties binnen organisatorische processen, en stel innovatieve oplossingen voor die de algehele functionaliteit van ICT-systemen verbeteren. Werken in een gestructureerde maar onvoorspelbare context met vage problemen, waarbij zowel de aanpak als de oplossingsruimte open zijn.'),
      ('Organisational processes', 'Advise', 1, 'Het geven van basisadvies over het organiseren van processen en informatie voor een nieuw, aangeschaft of aangepast ICT-systeem, waarbij de nadruk ligt op de algehele functionaliteit van zowel geautomatiseerde als niet-geautomatiseerde componenten. Opereren volgens algemene richtlijnen in een gestructureerde, voorspelbare context, en ervoor zorgen dat hun advies aansluit bij specifieke organisatiedoelen.'),
      ('Organisational processes', 'Advise', 2, 'Autonoom adviseren over het organiseren van processen en informatie voor ICT-systemen, waarbij problemen met zowel geautomatiseerde als niet-geautomatiseerde componenten worden aangepakt. Werk in een gestructureerde maar onvoorspelbare context, bied oplossingen met beperkte keuzemogelijkheden en zorg ervoor dat hun advies de doelstellingen van de organisatie ondersteunt.'),
      ('Organisational processes', 'Advise', 3, 'Geef zelfstandig uitgebreid advies over het organiseren van processen en informatie voor ICT-systemen, rekening houdend met complexe interacties tussen systeemcomponenten en organisatieprocessen. Werk in een gestructureerde maar onvoorspelbare context, pak vage problemen aan met een open benadering en zorg ervoor dat hun advies aansluit bij de doelstellingen van de organisatie.'),
      ('Organisational processes', 'Design', 1, 'Ontwerp een basis-ICT-systeem of een deel daarvan om specifieke organisatieprocessen te faciliteren op basis van duidelijk gedefinieerde eisen. Volg gevestigde richtlijnen en bekende oplossingen om ervoor te zorgen dat het systeem voldoet aan essentiële organisatiedoelen in een gestructureerde en voorspelbare context.'),
      ('Organisational processes', 'Design', 2, 'Ontwerp een ICT-systeem dat organisatieprocessen ondersteunt door zowel geautomatiseerde als niet-geautomatiseerde componenten te integreren. Ga in op de gebruikersvereisten en organisatiedoelen op basis van een grondige analyse van de vereisten, waarbij u rekening houdt met onvoorspelbaarheid in het proces. Kies uit een beperkt aantal ontwerpbenaderingen om een ​​effectief systeem te creëren dat aansluit bij de doelstellingen van de organisatie.'),
      ('Organisational processes', 'Design', 3, 'Ontwerp een alomvattend ICT-systeem om organisatorische processen te vergemakkelijken en zorg te dragen voor afstemming op de algemene organisatiedoelstellingen. Ontwikkel innovatieve oplossingen op basis van een gedetailleerde behoefteanalyse, rekening houdend met de interactie tussen geautomatiseerde en niet-geautomatiseerde componenten. Ga om met onvoorspelbare contexten en vage problemen en zorg ervoor dat het systeem organisatorische processen effectief ondersteunt en verbetert.'),
      ('Organisational processes', 'Realisation', 1, 'Creëer en test basiscomponenten van een ICT-systeem op basis van een bepaald ontwerp om specifieke organisatieprocessen te faciliteren. Volg vastgestelde procedures om ervoor te zorgen dat de systeemcomponenten voldoen aan vooraf gedefinieerde vereisten. Focus op het implementeren van eenvoudige functionaliteiten in een gestructureerde en voorspelbare context om organisatiedoelen te ondersteunen.'),
      ('Organisational processes', 'Realisation', 2, 'Op basis van een gedetailleerd ontwerp componenten van een ICT-systeem creëren en testen die zowel geautomatiseerde als niet-geautomatiseerde elementen integreren. Houd rekening met specifieke organisatorische vereisten en ga om met enige onvoorspelbaarheid tijdens de implementatie. Selecteer geschikte methoden om ervoor te zorgen dat de systeemcomponenten de beoogde organisatorische processen effectief faciliteren.'),
      ('Organisational processes', 'Realisation', 3, 'Creëer en test uitgebreide ICT-systemen, met zowel geautomatiseerde als niet-geautomatiseerde componenten, ter ondersteuning van organisatorische processen. Ontwikkel innovatieve oplossingen op basis van gedetailleerde ontwerpspecificaties, waarbij u rekening houdt met onvoorspelbare contexten en vage vereisten. Implementeer geavanceerde functionaliteiten die ervoor zorgen dat het systeem voldoet aan de bredere organisatiedoelen.'),
      ('Organisational processes', 'Manage&Control', 1, 'Beheer en bewaak basiscomponenten van een ICT-systeem om specifieke organisatieprocessen te faciliteren. Volg vastgestelde procedures om ervoor te zorgen dat de geautomatiseerde en niet-geautomatiseerde functionaliteiten van het systeem soepel werken en voldoen aan vooraf gedefinieerde organisatiedoelen. Werk binnen een gestructureerde en voorspelbare context om essentiële systeemoperaties te behouden.'),
      ('Organisational processes', 'Manage&Control', 2, 'Beheer, monitor en optimaliseer de ontwikkeling en inzet van ICT-systemen die organisatieprocessen ondersteunen. Houd rekening met specifieke organisatorische vereisten en ga om met enige onvoorspelbaarheid tijdens het proces. Selecteer geschikte methoden om de systeemprestaties te verbeteren en te zorgen voor afstemming op de doelstellingen van de organisatie.'),
      ('Organisational processes', 'Manage&Control', 3, 'Houdt toezicht op het beheer, de monitoring en de optimalisatie van uitgebreide ICT-systemen om organisatorische processen te vergemakkelijken. Ontwikkel en implementeer innovatieve oplossingen op basis van gedetailleerde prestatiegegevens en organisatorische feedback. Ga om met onvoorspelbare contexten en complexe problemen, zodat het systeem de algemene organisatiedoelen effectief ondersteunt en verbetert.')
    `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DROP TABLE IF EXISTS "competence_framework"`);
  }
}
